export enum Actions {
  POST = 'POST',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE'
}

export enum StatusCodes {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED'
}

export enum Services {
  AUTH = 'AUTH_SERVICE',
  USERS = 'USERS_SERVICE',
  FRIENDS = 'FRIENDS_SERVICE',
  REFRESH_TOKEN = 'REFRESH_TOKEN_SERVICE',
  REVIEWS = 'REVIEWS_SERVICE',
  PLACES = 'PLACES_SERVICE',
  IMAGE_STORAGE = 'IMAGE_STORAGE_SERVICE',
  PROFILE = 'PROFILE_SERVICE',
  FAVOURITES = 'FAVOURITES_SERVICE',
  GATEWAY_SESSION_MANAGER = 'GATEWAY_SESSION_MANAGER',
  COMMENTS = 'COMMENTS_SERVICE',
  NEWSFEED = 'NEWSFEED_SERVICE',
  PLACE_IMAGES = 'PLACE_IMAGE_SERVICE',
  NOTIFICATION = 'NOTIFICATION'
}

export enum StatusFriend {
  ME = 'ME',
  FRIEND = `FRIEND`,
  REQUESTED = 'REQUESTED',
  RESPONSE = 'RESPONSE',
  NOT_FOUND = 'NOT_FOUND'
}
